color0                #172526
color1                #D2696C
color2                #88B497
color3                #FFD7AA
color4                #91C4C0
color5                #F9ADA0
color6                #87CBB1
color7                #a1a790
color8                #568270
color9                #D2696C
color10               #88B497
color11               #FFD7AA
color12               #91C4C0
color13               #F9ADA0
color14               #87CBB1
color15               #DBD2C7
background            #172526
foreground            #DBD2C7
cursor                #DBD2C7
selection_background  #233935
selection_foreground #DBD2C7
